### ISSUE TITLE
Minimize dependencies

### ISSUE THREAD

**Issue by hoijui** [pawurb/mdbook-reading-time#1]
This tool has a total of more then 250 dependency crates. That seems a bit hefty to me, for such a simple tool.

Maybe we coudl try to incldue the dependencies like this instead?

```toml
mdbook = { version = "0.3.6", default-features = false }
```

to try to reduce this at least a bit?

**Comment by pawurb** [comment]
@hoijui thanks for an idea, released as `0.1.2`

**Comment by pawurb** [comment]
Before:

`cargo tree | wc -l => 379`

After:

`cargo tree | wc -l => 121`

**Comment by hoijui** [comment]
wow! :-)
that *is* an improvement!

**Comment by hoijui** [comment]
installing this new version, it now shows 90 dependencies! :-)
thank you!
